# properties

# Training properties
BATCH_SIZE = 64
LEARNING_RATE = 1e-4

# Image properties
PATCH_SIZE = 16
IMAGE_SIZE = 128
INTERPOL = 3
STRIPE_SIZE = (128, 16)
EMBEDDING_SIZE = 128
NO_OF_HEADS = 4
NO_OF_BLOCKS_TEXTURES = 2
NO_OF_BLOCKS_PRODUCTS = 1