# properties

# Training properties
BATCH_SIZE = 64
LEARNING_RATE = 1e-4
EPOCHS = 10

# Image properties
PATCH_SIZE = 16
IMAGE_SIZE = 128
INPUT_CHANNELS = 3
MVTEC_CLASSES = 2
# DEPTH = 2
MLP_RATIO = 4.
QKV_BIAS = True
DROPOUT_PROB = 0.
ATTENTION_DROPOUT = 0.
INTERPOL = 3
STRIPE_SIZE = (128, 16)
EMBEDDING_SIZE = 128
NO_OF_HEADS = 4
NO_OF_BLOCKS_TEXTURES = 2
NO_OF_BLOCKS_PRODUCTS = 1

SAVE_PATH = './mvtec_net.pth'
